project:
  type: website
  output-dir: docs

website:
  title: "temp_website"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: data_visualisation.qmd
      - href: reflection.qmd
        text: Reflection
      

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



